### ISSUE TITLE
configparser.MissingSectionHeaderError: File contains no section headers.

### ISSUE THREAD

**Issue by ontologist** [KRR-Oxford/OWL2Vec-Star#9]
Your operating system name and version.
MacOSX Monterrey version 12.6.1

Any details about your local setup that might be helpful in troubleshooting.
Running it on Google Colab with Python 3.8

Detailed steps to reproduce the bug.

```
pip install owl2vec_star
import owl2vec_star
owl2vec_star standalone --config_file /content/drive/MyDrive/data/ontologies/laptop_ontology/laptop.owl
```

```
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "/usr/local/bin/owl2vec_star", line 33, in <module>
    sys.exit(load_entry_point('owl2vec-star==0.2.1', 'console_scripts', 'owl2vec_star')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/owl2vec_star/cli.py", line 34, in standalone
    config.read(click.format_filename(config_file))
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/content/drive/MyDrive/data/ontologies/laptop_ontology/laptop.owl', line: 1
'<?xml version="1.0"?>\n'
```

It doesn't matter what ontology I use, I get the same error. Whether I install via pip or from sources is the same error

**Comment by ontologist** [comment]
I was able to resolve this issue by updating gensim and resolving other issues that arised from that.

**Comment by ernestojimenezruiz** [comment]
Great! Apologies for the slow reply.
